# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/configurablereceiver_0/configurablereceiver_0.xci
# IP: The module: 'configurablereceiver_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_c_addsub_v12_0_i0/configurablereceiver_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_c_addsub_v12_0_i0 || ORIG_REF_NAME==configurablereceiver_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_c_addsub_v12_0_i1/configurablereceiver_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_c_addsub_v12_0_i1 || ORIG_REF_NAME==configurablereceiver_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_cic_compiler_v4_0_i0/configurablereceiver_cic_compiler_v4_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_cic_compiler_v4_0_i0 || ORIG_REF_NAME==configurablereceiver_cic_compiler_v4_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_cordic_v6_0_i0/configurablereceiver_cordic_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_cordic_v6_0_i0 || ORIG_REF_NAME==configurablereceiver_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_dds_compiler_v6_0_i0/configurablereceiver_dds_compiler_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_dds_compiler_v6_0_i0 || ORIG_REF_NAME==configurablereceiver_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i0/configurablereceiver_fir_compiler_v7_2_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i0 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i1/configurablereceiver_fir_compiler_v7_2_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i1 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i1} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i2/configurablereceiver_fir_compiler_v7_2_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i2 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i2} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i3/configurablereceiver_fir_compiler_v7_2_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i3 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i3} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_mult_gen_v12_0_i0/configurablereceiver_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_mult_gen_v12_0_i0 || ORIG_REF_NAME==configurablereceiver_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i0 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i1 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i2/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i2 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i3/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i3 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/constrs/configurablereceiver.xdc
# XDC: The top module name and the constraint reference have the same name: 'configurablereceiver_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/configurablereceiver_0/configurablereceiver_0.xci
# IP: The module: 'configurablereceiver_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_c_addsub_v12_0_i0/configurablereceiver_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_c_addsub_v12_0_i0 || ORIG_REF_NAME==configurablereceiver_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_c_addsub_v12_0_i1/configurablereceiver_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_c_addsub_v12_0_i1 || ORIG_REF_NAME==configurablereceiver_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_cic_compiler_v4_0_i0/configurablereceiver_cic_compiler_v4_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_cic_compiler_v4_0_i0 || ORIG_REF_NAME==configurablereceiver_cic_compiler_v4_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_cordic_v6_0_i0/configurablereceiver_cordic_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_cordic_v6_0_i0 || ORIG_REF_NAME==configurablereceiver_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_dds_compiler_v6_0_i0/configurablereceiver_dds_compiler_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_dds_compiler_v6_0_i0 || ORIG_REF_NAME==configurablereceiver_dds_compiler_v6_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i0/configurablereceiver_fir_compiler_v7_2_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i0 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i1/configurablereceiver_fir_compiler_v7_2_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i1 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i1} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i2/configurablereceiver_fir_compiler_v7_2_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i2 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i2} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i3/configurablereceiver_fir_compiler_v7_2_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i3 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i3} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_mult_gen_v12_0_i0/configurablereceiver_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==configurablereceiver_mult_gen_v12_0_i0 || ORIG_REF_NAME==configurablereceiver_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i0 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i1 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i2/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i2 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/configurablereceiver_fir_compiler_v7_2_i3/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==configurablereceiver_fir_compiler_v7_2_i3 || ORIG_REF_NAME==configurablereceiver_fir_compiler_v7_2_i3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/configurablereceiver_0/constrs/configurablereceiver.xdc
# XDC: The top module name and the constraint reference have the same name: 'configurablereceiver_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
