# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/fftmodule_0/fftmodule_0.xci
# IP: The module: 'fftmodule_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/fftmodule_0/fftmodule_cordic_v6_0_i0/fftmodule_cordic_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fftmodule_cordic_v6_0_i0 || ORIG_REF_NAME==fftmodule_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/fftmodule_0/fftmodule_xfft_v9_1_i0/fftmodule_xfft_v9_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fftmodule_xfft_v9_1_i0 || ORIG_REF_NAME==fftmodule_xfft_v9_1_i0} -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/fftmodule_0/constrs/fftmodule.xdc
# XDC: The top module name and the constraint reference have the same name: 'fftmodule_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/fftmodule_0/fftmodule_0.xci
# IP: The module: 'fftmodule_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/fftmodule_0/fftmodule_cordic_v6_0_i0/fftmodule_cordic_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fftmodule_cordic_v6_0_i0 || ORIG_REF_NAME==fftmodule_cordic_v6_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/fftmodule_0/fftmodule_xfft_v9_1_i0/fftmodule_xfft_v9_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fftmodule_xfft_v9_1_i0 || ORIG_REF_NAME==fftmodule_xfft_v9_1_i0} -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/fftmodule_0/constrs/fftmodule.xdc
# XDC: The top module name and the constraint reference have the same name: 'fftmodule_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
