# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/decimator_0/decimator_0.xci
# IP: The module: 'decimator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/decimator_cic_compiler_v4_0_i0/decimator_cic_compiler_v4_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decimator_cic_compiler_v4_0_i0 || ORIG_REF_NAME==decimator_cic_compiler_v4_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/decimator_fir_compiler_v7_2_i0/decimator_fir_compiler_v7_2_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decimator_fir_compiler_v7_2_i0 || ORIG_REF_NAME==decimator_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/decimator_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==decimator_fir_compiler_v7_2_i0 || ORIG_REF_NAME==decimator_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/constrs/decimator.xdc
# XDC: The top module name and the constraint reference have the same name: 'decimator_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/decimator_0/decimator_0.xci
# IP: The module: 'decimator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/decimator_cic_compiler_v4_0_i0/decimator_cic_compiler_v4_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decimator_cic_compiler_v4_0_i0 || ORIG_REF_NAME==decimator_cic_compiler_v4_0_i0} -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/decimator_fir_compiler_v7_2_i0/decimator_fir_compiler_v7_2_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decimator_fir_compiler_v7_2_i0 || ORIG_REF_NAME==decimator_fir_compiler_v7_2_i0} -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/decimator_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==decimator_fir_compiler_v7_2_i0 || ORIG_REF_NAME==decimator_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/decimator_0/constrs/decimator.xdc
# XDC: The top module name and the constraint reference have the same name: 'decimator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
