# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/rom_sine/rom_sine.xci
# IP: The module: 'rom_sine' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/rom_sine/rom_sine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sine'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/rom_sine/rom_sine.xci
# IP: The module: 'rom_sine' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/rom_sine/rom_sine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_sine'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
