set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data_busy]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data_enable]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data_spi_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports conf_cs]
set_property IOSTANDARD LVCMOS33 [get_ports conf_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports conf_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch2_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ch1_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[0]}]
set_property PACKAGE_PIN A15 [get_ports rstn]
set_property PACKAGE_PIN A14 [get_ports adc_data_busy]
set_property PACKAGE_PIN A16 [get_ports adc_data_enable]
set_property PACKAGE_PIN A21 [get_ports adc_data_spi_clk]
set_property PACKAGE_PIN B22 [get_ports adc_data_spi_mosi]
set_property PACKAGE_PIN B15 [get_ports conf_cs]
set_property PACKAGE_PIN A18 [get_ports conf_spi_mosi]
set_property PACKAGE_PIN R3 [get_ports clk]
set_property PACKAGE_PIN N2 [get_ports {adc_in[15]}]
set_property PACKAGE_PIN P2 [get_ports {adc_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {adc_in[13]}]
set_property PACKAGE_PIN V2 [get_ports {adc_in[12]}]
set_property PACKAGE_PIN W2 [get_ports {adc_in[6]}]
set_property PACKAGE_PIN Y2 [get_ports {adc_in[4]}]
set_property PACKAGE_PIN AA1 [get_ports {adc_in[3]}]
set_property PACKAGE_PIN AB1 [get_ports {adc_in[2]}]
set_property PACKAGE_PIN AB2 [get_ports {adc_in[1]}]
set_property PACKAGE_PIN AA3 [get_ports {adc_in[0]}]
set_property PACKAGE_PIN AA18 [get_ports {dac_ch1_data[0]}]
set_property PACKAGE_PIN AB20 [get_ports {dac_ch1_data[1]}]
set_property PACKAGE_PIN AA20 [get_ports {dac_ch1_data[2]}]
set_property PACKAGE_PIN AB21 [get_ports {dac_ch1_data[3]}]
set_property PACKAGE_PIN AA21 [get_ports {dac_ch1_data[4]}]
set_property PACKAGE_PIN AB22 [get_ports {dac_ch1_data[5]}]
set_property PACKAGE_PIN Y21 [get_ports {dac_ch1_data[6]}]
set_property PACKAGE_PIN Y22 [get_ports {dac_ch1_data[7]}]
set_property PACKAGE_PIN W21 [get_ports {dac_ch1_data[8]}]
set_property PACKAGE_PIN W22 [get_ports {dac_ch1_data[9]}]
set_property PACKAGE_PIN V22 [get_ports {dac_ch1_data[10]}]
set_property PACKAGE_PIN Y19 [get_ports {dac_ch1_data[11]}]
set_property PACKAGE_PIN W19 [get_ports {dac_ch1_data[12]}]
set_property PACKAGE_PIN W20 [get_ports {dac_ch1_data[13]}]
set_property PACKAGE_PIN T15 [get_ports {dac_ch2_data[0]}]
set_property PACKAGE_PIN V14 [get_ports {dac_ch2_data[1]}]
set_property PACKAGE_PIN W14 [get_ports {dac_ch2_data[2]}]
set_property PACKAGE_PIN V15 [get_ports {dac_ch2_data[3]}]
set_property PACKAGE_PIN W15 [get_ports {dac_ch2_data[4]}]
set_property PACKAGE_PIN Y14 [get_ports {dac_ch2_data[5]}]
set_property PACKAGE_PIN AA14 [get_ports {dac_ch2_data[6]}]
set_property PACKAGE_PIN W16 [get_ports {dac_ch2_data[7]}]
set_property PACKAGE_PIN Y16 [get_ports {dac_ch2_data[8]}]
set_property PACKAGE_PIN AB15 [get_ports {dac_ch2_data[9]}]
set_property PACKAGE_PIN AA15 [get_ports {dac_ch2_data[10]}]
set_property PACKAGE_PIN AB16 [get_ports {dac_ch2_data[11]}]
set_property PACKAGE_PIN AA16 [get_ports {dac_ch2_data[12]}]
set_property PACKAGE_PIN AB17 [get_ports {dac_ch2_data[13]}]

set_property IOSTANDARD LVCMOS33 [get_ports dac1_sleep]
set_property IOSTANDARD LVCMOS33 [get_ports dac2_sleep]
set_property PACKAGE_PIN U15 [get_ports dac2_sleep]
set_property PACKAGE_PIN AB18 [get_ports dac1_sleep]



create_clock -period 24.414 -name clk -waveform {0.000 12.207} [get_ports clk]
set_input_delay -clock [get_clocks clk] -min -add_delay 12.000 [get_ports {adc_in[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 14.000 [get_ports {adc_in[*]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]


set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports rst_phase]
set_property PACKAGE_PIN B17 [get_ports rst_phase]
set_property PACKAGE_PIN B18 [get_ports conf_spi_clk]


set_property PACKAGE_PIN R1 [get_ports {adc_in[11]}]
set_property PACKAGE_PIN T1 [get_ports {adc_in[10]}]
set_property PACKAGE_PIN U1 [get_ports {adc_in[9]}]
set_property PACKAGE_PIN U2 [get_ports {adc_in[8]}]
set_property PACKAGE_PIN W1 [get_ports {adc_in[7]}]
set_property PACKAGE_PIN Y1 [get_ports {adc_in[5]}]
