set_property PACKAGE_PIN R3 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_in[0]}]
set_property PACKAGE_PIN N2 [get_ports {adc_in[15]}]
set_property PACKAGE_PIN P2 [get_ports {adc_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {adc_in[13]}]
set_property PACKAGE_PIN V2 [get_ports {adc_in[12]}]
set_property PACKAGE_PIN R1 [get_ports {adc_in[11]}]
set_property PACKAGE_PIN U1 [get_ports {adc_in[9]}]
set_property PACKAGE_PIN T1 [get_ports {adc_in[10]}]
set_property PACKAGE_PIN U2 [get_ports {adc_in[8]}]
set_property PACKAGE_PIN W1 [get_ports {adc_in[7]}]
set_property PACKAGE_PIN W2 [get_ports {adc_in[6]}]
set_property PACKAGE_PIN Y1 [get_ports {adc_in[5]}]
set_property PACKAGE_PIN Y2 [get_ports {adc_in[4]}]
set_property PACKAGE_PIN AA1 [get_ports {adc_in[3]}]
set_property PACKAGE_PIN AB1 [get_ports {adc_in[2]}]
set_property PACKAGE_PIN AB2 [get_ports {adc_in[1]}]
set_property PACKAGE_PIN AA3 [get_ports {adc_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports in_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports in_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports out_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports out_spi_clk]
set_property PACKAGE_PIN A21 [get_ports out_spi_clk]
set_property PACKAGE_PIN B22 [get_ports out_MOSI]
set_property PACKAGE_PIN A14 [get_ports in_MOSI]
set_property PACKAGE_PIN B16 [get_ports in_spi_clk]
set_property PACKAGE_PIN A16 [get_ports enable]
create_clock -period 25.000 -name clk -waveform {0.000 12.500} [get_ports clk]
set_input_delay -clock [get_clocks clk] -min -add_delay 6.000 [get_ports {adc_in[*]}]
set_input_delay -clock [get_clocks clk] -max -add_delay 10.000 [get_ports {adc_in[*]}]


set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 8 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {dac[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac[0]}]
set_property PACKAGE_PIN T15 [get_ports {dac[0]}]
set_property PACKAGE_PIN V14 [get_ports {dac[1]}]
set_property PACKAGE_PIN W14 [get_ports {dac[2]}]
set_property PACKAGE_PIN V15 [get_ports {dac[3]}]
set_property PACKAGE_PIN W15 [get_ports {dac[4]}]
set_property PACKAGE_PIN Y14 [get_ports {dac[5]}]
set_property PACKAGE_PIN Y16 [get_ports {dac[8]}]
set_property PACKAGE_PIN W16 [get_ports {dac[7]}]
set_property PACKAGE_PIN AA14 [get_ports {dac[6]}]
set_property PACKAGE_PIN AB15 [get_ports {dac[9]}]
set_property PACKAGE_PIN AA15 [get_ports {dac[10]}]
set_property PACKAGE_PIN AB16 [get_ports {dac[11]}]
set_property PACKAGE_PIN AA16 [get_ports {dac[12]}]
set_property PACKAGE_PIN AB17 [get_ports {dac[13]}]

set_property IOSTANDARD LVCMOS33 [get_ports dac_sleep]
set_property PACKAGE_PIN U15 [get_ports dac_sleep]

set_property PACKAGE_PIN AA3 [get_ports {adc_data[0]}]
set_property PACKAGE_PIN AB2 [get_ports {adc_data[1]}]
set_property PACKAGE_PIN AB1 [get_ports {adc_data[2]}]
set_property PACKAGE_PIN AA1 [get_ports {adc_data[3]}]
set_property PACKAGE_PIN Y2 [get_ports {adc_data[4]}]
set_property PACKAGE_PIN Y1 [get_ports {adc_data[5]}]
set_property PACKAGE_PIN W2 [get_ports {adc_data[6]}]
set_property PACKAGE_PIN W1 [get_ports {adc_data[7]}]
set_property PACKAGE_PIN U2 [get_ports {adc_data[8]}]
set_property PACKAGE_PIN U1 [get_ports {adc_data[9]}]
set_property PACKAGE_PIN T1 [get_ports {adc_data[10]}]
set_property PACKAGE_PIN R1 [get_ports {adc_data[11]}]
set_property PACKAGE_PIN V2 [get_ports {adc_data[12]}]
set_property PACKAGE_PIN R2 [get_ports {adc_data[13]}]
set_property PACKAGE_PIN P2 [get_ports {adc_data[14]}]
set_property PACKAGE_PIN N2 [get_ports {adc_data[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]
set_property PACKAGE_PIN B15 [get_ports cs]

set_property IOSTANDARD LVCMOS33 [get_ports busy]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property PACKAGE_PIN A14 [get_ports busy]
set_property PACKAGE_PIN A21 [get_ports spi_clk]
set_property PACKAGE_PIN B22 [get_ports spi_mosi]

set_property PACKAGE_PIN A15 [get_ports rstn]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
