# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/DDS_ila/DDS_ila.xci
# IP: The module: 'DDS_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/DDS_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ila'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/DDS_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/DDS_ila/DDS_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.srcs/sources_1/ip/DDS_ila/DDS_ila.xci
# IP: The module: 'DDS_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/DDS_ila/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/DDS_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/RisingEntropy/Documents/Projects/FPGA/SPI/SPI.gen/sources_1/ip/DDS_ila/DDS_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
