# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints1.xdc

# IP: ip/fifo_generator_1/fifo_generator_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# IP: ip/decimator_buffer_fifo/decimator_buffer_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==decimator_buffer_fifo || ORIG_REF_NAME==decimator_buffer_fifo} -quiet] -quiet
