# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints1.xdc

# IP: ip/SignalSplitter_ila/SignalSplitter_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SignalSplitter_ila || ORIG_REF_NAME==SignalSplitter_ila} -quiet] -quiet
